// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vaxi4_top_tb__Syms.h"


VL_ATTR_COLD void Vaxi4_top_tb___024root__trace_init_sub__TOP__0(Vaxi4_top_tb___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vaxi4_top_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vaxi4_top_tb___024root__trace_init_sub__TOP__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->pushPrefix("axi4_top_tb", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+171,0,"clk",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+172,0,"resetn",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+4,0,"write_transaction_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+5,0,"read_transaction_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+6,0,"write_addr_handshake_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+7,0,"read_addr_handshake_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+8,0,"write_resp_handshake_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+9,0,"read_data_handshake_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+10,0,"assertion_pass_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+11,0,"assertion_fail_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+12,0,"warmup_cycles",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+174,0,"WARMUP_PERIOD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBit(c+13,0,"warmup_complete",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+14,0,"awvalid_prev",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+15,0,"arvalid_prev",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"wvalid_prev",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+17,0,"bvalid_prev",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+18,0,"rvalid_prev",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+19,0,"awready_prev",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+20,0,"arready_prev",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+21,0,"wready_prev",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+22,0,"bready_prev",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+23,0,"rready_prev",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+24,0,"total_aw_handshakes",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+25,0,"total_w_handshakes",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+26,0,"total_b_handshakes",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+27,0,"total_ar_handshakes",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+28,0,"total_r_handshakes",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+29,0,"total_wlast_seen",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+30,0,"total_rlast_seen",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBit(c+31,0,"awvalid_ever_seen",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+32,0,"arvalid_ever_seen",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+33,0,"wvalid_ever_seen",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+34,0,"bvalid_ever_seen",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+35,0,"rvalid_ever_seen",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+36,0,"write_beat_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+37,0,"write_burst_len",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBit(c+38,0,"write_burst_active",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+39,0,"read_beat_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+40,0,"read_burst_len",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBit(c+41,0,"read_burst_active",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+42,0,"aw_seen",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+43,0,"wlast_handshake_seen",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+44,0,"aw_timeout_counter",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+45,0,"w_timeout_counter",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+175,0,"RESPONSE_TIMEOUT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+46,0,"pending_ar_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+47,0,"ar_no_data_counter",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBit(c+48,0,"ever_saw_rvalid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+176,0,"VALID_ACTIVITY_TIMEOUT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+49,0,"ar_activity_counter",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+50,0,"aw_activity_counter",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBit(c+51,0,"ar_activity_checked",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+52,0,"aw_activity_checked",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+53,0,"reset_checked",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+54,0,"write_addr_low_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+55,0,"write_addr_mid_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+56,0,"write_addr_high_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+57,0,"write_burst_fixed_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+58,0,"write_burst_incr_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+59,0,"write_burst_wrap_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+60,0,"write_size_byte_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+61,0,"write_size_halfword_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+62,0,"write_size_word_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+63,0,"write_resp_okay_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+64,0,"write_resp_exokay_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+65,0,"write_resp_slverr_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+66,0,"write_resp_decerr_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+67,0,"read_addr_low_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+68,0,"read_addr_mid_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+69,0,"read_addr_high_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+70,0,"read_burst_fixed_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+71,0,"read_burst_incr_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+72,0,"read_burst_wrap_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+73,0,"read_resp_okay_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+74,0,"read_resp_exokay_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+75,0,"read_resp_slverr_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+76,0,"read_resp_decerr_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+77,0,"aw_handshake_valid_ready_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+78,0,"w_handshake_valid_ready_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+79,0,"b_handshake_valid_ready_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+80,0,"ar_handshake_valid_ready_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+81,0,"r_handshake_valid_ready_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+82,0,"interrupt_idle_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+83,0,"interrupt_pending_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+84,0,"interrupt_acknowledged_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBit(c+85,0,"interrupt_req_prev",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+86,0,"interrupt_ack_prev",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("dut", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+171,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+172,0,"resetn",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+112,0,"axi_awaddr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+113,0,"axi_awlen",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+114,0,"axi_awsize",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+115,0,"axi_awburst",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+116,0,"axi_awvalid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+117,0,"axi_awready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+118,0,"axi_wdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+119,0,"axi_wstrb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+120,0,"axi_wlast",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+121,0,"axi_wvalid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+122,0,"axi_wready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+123,0,"axi_bresp",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+124,0,"axi_bvalid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+125,0,"axi_bready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+126,0,"axi_araddr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+127,0,"axi_arlen",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+128,0,"axi_arsize",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+129,0,"axi_arburst",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+130,0,"axi_arvalid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+131,0,"axi_arready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+132,0,"axi_rdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+133,0,"axi_rresp",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+134,0,"axi_rlast",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+135,0,"axi_rvalid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+136,0,"axi_rready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+177,0,"interrupt_req",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+137,0,"interrupt_ack",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("coverage_monitor", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+178,0,"ADDR_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+178,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+171,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+172,0,"resetn",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+112,0,"awaddr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+113,0,"awlen",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+114,0,"awsize",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+115,0,"awburst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+116,0,"awvalid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+117,0,"awready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+118,0,"wdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+119,0,"wstrb",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+120,0,"wlast",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+121,0,"wvalid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+122,0,"wready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+123,0,"bresp",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+124,0,"bvalid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+125,0,"bready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+126,0,"araddr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+127,0,"arlen",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+128,0,"arsize",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+129,0,"arburst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+130,0,"arvalid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+131,0,"arready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+132,0,"rdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+133,0,"rresp",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+134,0,"rlast",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+135,0,"rvalid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+136,0,"rready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+87,0,"burst_fixed_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+88,0,"burst_incr_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+89,0,"burst_wrap_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+90,0,"single_beat_write_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+91,0,"multi_beat_write_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+92,0,"single_beat_read_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+93,0,"multi_beat_read_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+94,0,"resp_okay_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+95,0,"resp_exokay_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+96,0,"resp_slverr_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+97,0,"resp_decerr_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+98,0,"aw_handshake_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+99,0,"w_handshake_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+100,0,"b_handshake_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+101,0,"ar_handshake_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+102,0,"r_handshake_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+103,0,"addr_region0_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+104,0,"addr_region1_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+105,0,"addr_region2_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+106,0,"addr_region3_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+107,0,"addr_out_of_range_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+108,0,"wstrb_full_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+109,0,"wstrb_partial_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+110,0,"wlast_asserted_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+111,0,"rlast_asserted_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+179,0,"FIXED",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+180,0,"INCR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+181,0,"WRAP",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+179,0,"OKAY",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+180,0,"EXOKAY",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+181,0,"SLVERR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+182,0,"DECERR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+183,0,"TOTAL_COVERAGE_BINS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("unnamedblk1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+1,0,"bins_hit",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declDouble(c+2,0,"coverage_pct",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::DOUBLE, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("interrupt_ctrl", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+171,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+172,0,"resetn",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+177,0,"interrupt_req",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+137,0,"interrupt_ack",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+138,0,"state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+139,0,"next_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->popPrefix();
    tracep->pushPrefix("master", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+171,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+172,0,"resetn",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+112,0,"axi_awaddr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+113,0,"axi_awlen",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+114,0,"axi_awsize",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+115,0,"axi_awburst",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+116,0,"axi_awvalid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+117,0,"axi_awready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+118,0,"axi_wdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+119,0,"axi_wstrb",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+120,0,"axi_wlast",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+121,0,"axi_wvalid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+122,0,"axi_wready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+123,0,"axi_bresp",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+124,0,"axi_bvalid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+125,0,"axi_bready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+126,0,"axi_araddr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+127,0,"axi_arlen",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+128,0,"axi_arsize",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+129,0,"axi_arburst",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+130,0,"axi_arvalid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+131,0,"axi_arready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+132,0,"axi_rdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+133,0,"axi_rresp",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+134,0,"axi_rlast",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+135,0,"axi_rvalid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+136,0,"axi_rready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+140,0,"state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+141,0,"next_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+142,0,"write_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+143,0,"write_base_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+144,0,"write_length",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+145,0,"write_size",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+146,0,"write_burst",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+147,0,"write_in_progress",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+148,0,"read_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+149,0,"read_base_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+150,0,"read_length",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+151,0,"read_size",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+152,0,"read_burst",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+153,0,"read_in_progress",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+179,0,"FIXED",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+180,0,"INCR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+181,0,"WRAP",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+179,0,"OKAY",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+180,0,"EXOKAY",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+181,0,"SLVERR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+182,0,"DECERR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->popPrefix();
    tracep->pushPrefix("slave", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+171,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+172,0,"resetn",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+112,0,"axi_awaddr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+113,0,"axi_awlen",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+114,0,"axi_awsize",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+115,0,"axi_awburst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+116,0,"axi_awvalid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+117,0,"axi_awready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+118,0,"axi_wdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+119,0,"axi_wstrb",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+120,0,"axi_wlast",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+121,0,"axi_wvalid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+122,0,"axi_wready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+123,0,"axi_bresp",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+124,0,"axi_bvalid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+125,0,"axi_bready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+126,0,"axi_araddr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+127,0,"axi_arlen",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+128,0,"axi_arsize",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+129,0,"axi_arburst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+130,0,"axi_arvalid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+131,0,"axi_arready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+132,0,"axi_rdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+133,0,"axi_rresp",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+134,0,"axi_rlast",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+135,0,"axi_rvalid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+136,0,"axi_rready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+184,0,"MEM_SIZE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+154,0,"write_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+155,0,"write_len",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+156,0,"write_size",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+157,0,"write_burst",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+158,0,"write_addr_accepted",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+159,0,"write_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+160,0,"write_in_progress",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+161,0,"write_data_accepted",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+162,0,"write_response_pending",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+163,0,"write_response_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+164,0,"current_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+165,0,"addr_offset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+166,0,"byte_size",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+167,0,"wrap_boundary",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+168,0,"aligned_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+169,0,"mem_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+179,0,"OKAY",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+180,0,"EXOKAY",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+181,0,"SLVERR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+182,0,"DECERR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+179,0,"FIXED",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+180,0,"INCR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+181,0,"WRAP",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->pushPrefix("unnamedblk1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+173,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("unnamedblk2", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+170,0,"read_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vaxi4_top_tb___024root__trace_init_top(Vaxi4_top_tb___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vaxi4_top_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vaxi4_top_tb___024root__trace_init_top\n"); );
    // Body
    Vaxi4_top_tb___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vaxi4_top_tb___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vaxi4_top_tb___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vaxi4_top_tb___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vaxi4_top_tb___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vaxi4_top_tb___024root__trace_register(Vaxi4_top_tb___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vaxi4_top_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vaxi4_top_tb___024root__trace_register\n"); );
    // Body
    tracep->addConstCb(&Vaxi4_top_tb___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vaxi4_top_tb___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vaxi4_top_tb___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vaxi4_top_tb___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vaxi4_top_tb___024root__trace_const_0_sub_0(Vaxi4_top_tb___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vaxi4_top_tb___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vaxi4_top_tb___024root__trace_const_0\n"); );
    // Init
    Vaxi4_top_tb___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vaxi4_top_tb___024root*>(voidSelf);
    Vaxi4_top_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vaxi4_top_tb___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vaxi4_top_tb___024root__trace_const_0_sub_0(Vaxi4_top_tb___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    Vaxi4_top_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vaxi4_top_tb___024root__trace_const_0_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullIData(oldp+174,(1U),32);
    bufp->fullIData(oldp+175,(0x64U),32);
    bufp->fullIData(oldp+176,(0x1f4U),32);
    bufp->fullBit(oldp+177,(vlSelf->axi4_top_tb__DOT__dut__DOT__interrupt_req));
    bufp->fullIData(oldp+178,(0x20U),32);
    bufp->fullCData(oldp+179,(0U),2);
    bufp->fullCData(oldp+180,(1U),2);
    bufp->fullCData(oldp+181,(2U),2);
    bufp->fullCData(oldp+182,(3U),2);
    bufp->fullIData(oldp+183,(0x18U),32);
    bufp->fullIData(oldp+184,(0x100U),32);
}

VL_ATTR_COLD void Vaxi4_top_tb___024root__trace_full_0_sub_0(Vaxi4_top_tb___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vaxi4_top_tb___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vaxi4_top_tb___024root__trace_full_0\n"); );
    // Init
    Vaxi4_top_tb___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vaxi4_top_tb___024root*>(voidSelf);
    Vaxi4_top_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vaxi4_top_tb___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vaxi4_top_tb___024root__trace_full_0_sub_0(Vaxi4_top_tb___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    Vaxi4_top_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vaxi4_top_tb___024root__trace_full_0_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullIData(oldp+1,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__unnamedblk1__DOT__bins_hit),32);
    bufp->fullDouble(oldp+2,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__unnamedblk1__DOT__coverage_pct));
    bufp->fullIData(oldp+4,(vlSelf->axi4_top_tb__DOT__write_transaction_count),32);
    bufp->fullIData(oldp+5,(vlSelf->axi4_top_tb__DOT__read_transaction_count),32);
    bufp->fullIData(oldp+6,(vlSelf->axi4_top_tb__DOT__write_addr_handshake_count),32);
    bufp->fullIData(oldp+7,(vlSelf->axi4_top_tb__DOT__read_addr_handshake_count),32);
    bufp->fullIData(oldp+8,(vlSelf->axi4_top_tb__DOT__write_resp_handshake_count),32);
    bufp->fullIData(oldp+9,(vlSelf->axi4_top_tb__DOT__read_data_handshake_count),32);
    bufp->fullIData(oldp+10,(vlSelf->axi4_top_tb__DOT__assertion_pass_count),32);
    bufp->fullIData(oldp+11,(vlSelf->axi4_top_tb__DOT__assertion_fail_count),32);
    bufp->fullIData(oldp+12,(vlSelf->axi4_top_tb__DOT__warmup_cycles),32);
    bufp->fullBit(oldp+13,((1U <= vlSelf->axi4_top_tb__DOT__warmup_cycles)));
    bufp->fullBit(oldp+14,(vlSelf->axi4_top_tb__DOT__awvalid_prev));
    bufp->fullBit(oldp+15,(vlSelf->axi4_top_tb__DOT__arvalid_prev));
    bufp->fullBit(oldp+16,(vlSelf->axi4_top_tb__DOT__wvalid_prev));
    bufp->fullBit(oldp+17,(vlSelf->axi4_top_tb__DOT__bvalid_prev));
    bufp->fullBit(oldp+18,(vlSelf->axi4_top_tb__DOT__rvalid_prev));
    bufp->fullBit(oldp+19,(vlSelf->axi4_top_tb__DOT__awready_prev));
    bufp->fullBit(oldp+20,(vlSelf->axi4_top_tb__DOT__arready_prev));
    bufp->fullBit(oldp+21,(vlSelf->axi4_top_tb__DOT__wready_prev));
    bufp->fullBit(oldp+22,(vlSelf->axi4_top_tb__DOT__bready_prev));
    bufp->fullBit(oldp+23,(vlSelf->axi4_top_tb__DOT__rready_prev));
    bufp->fullIData(oldp+24,(vlSelf->axi4_top_tb__DOT__total_aw_handshakes),32);
    bufp->fullIData(oldp+25,(vlSelf->axi4_top_tb__DOT__total_w_handshakes),32);
    bufp->fullIData(oldp+26,(vlSelf->axi4_top_tb__DOT__total_b_handshakes),32);
    bufp->fullIData(oldp+27,(vlSelf->axi4_top_tb__DOT__total_ar_handshakes),32);
    bufp->fullIData(oldp+28,(vlSelf->axi4_top_tb__DOT__total_r_handshakes),32);
    bufp->fullIData(oldp+29,(vlSelf->axi4_top_tb__DOT__total_wlast_seen),32);
    bufp->fullIData(oldp+30,(vlSelf->axi4_top_tb__DOT__total_rlast_seen),32);
    bufp->fullBit(oldp+31,(vlSelf->axi4_top_tb__DOT__awvalid_ever_seen));
    bufp->fullBit(oldp+32,(vlSelf->axi4_top_tb__DOT__arvalid_ever_seen));
    bufp->fullBit(oldp+33,(vlSelf->axi4_top_tb__DOT__wvalid_ever_seen));
    bufp->fullBit(oldp+34,(vlSelf->axi4_top_tb__DOT__bvalid_ever_seen));
    bufp->fullBit(oldp+35,(vlSelf->axi4_top_tb__DOT__rvalid_ever_seen));
    bufp->fullIData(oldp+36,(vlSelf->axi4_top_tb__DOT__write_beat_count),32);
    bufp->fullIData(oldp+37,(vlSelf->axi4_top_tb__DOT__write_burst_len),32);
    bufp->fullBit(oldp+38,(vlSelf->axi4_top_tb__DOT__write_burst_active));
    bufp->fullIData(oldp+39,(vlSelf->axi4_top_tb__DOT__read_beat_count),32);
    bufp->fullIData(oldp+40,(vlSelf->axi4_top_tb__DOT__read_burst_len),32);
    bufp->fullBit(oldp+41,(vlSelf->axi4_top_tb__DOT__read_burst_active));
    bufp->fullBit(oldp+42,(vlSelf->axi4_top_tb__DOT__aw_seen));
    bufp->fullBit(oldp+43,(vlSelf->axi4_top_tb__DOT__wlast_handshake_seen));
    bufp->fullIData(oldp+44,(vlSelf->axi4_top_tb__DOT__aw_timeout_counter),32);
    bufp->fullIData(oldp+45,(vlSelf->axi4_top_tb__DOT__w_timeout_counter),32);
    bufp->fullIData(oldp+46,(vlSelf->axi4_top_tb__DOT__pending_ar_count),32);
    bufp->fullIData(oldp+47,(vlSelf->axi4_top_tb__DOT__ar_no_data_counter),32);
    bufp->fullBit(oldp+48,(vlSelf->axi4_top_tb__DOT__ever_saw_rvalid));
    bufp->fullIData(oldp+49,(vlSelf->axi4_top_tb__DOT__ar_activity_counter),32);
    bufp->fullIData(oldp+50,(vlSelf->axi4_top_tb__DOT__aw_activity_counter),32);
    bufp->fullBit(oldp+51,(vlSelf->axi4_top_tb__DOT__ar_activity_checked));
    bufp->fullBit(oldp+52,(vlSelf->axi4_top_tb__DOT__aw_activity_checked));
    bufp->fullBit(oldp+53,(vlSelf->axi4_top_tb__DOT__reset_checked));
    bufp->fullIData(oldp+54,(vlSelf->axi4_top_tb__DOT__write_addr_low_count),32);
    bufp->fullIData(oldp+55,(vlSelf->axi4_top_tb__DOT__write_addr_mid_count),32);
    bufp->fullIData(oldp+56,(vlSelf->axi4_top_tb__DOT__write_addr_high_count),32);
    bufp->fullIData(oldp+57,(vlSelf->axi4_top_tb__DOT__write_burst_fixed_count),32);
    bufp->fullIData(oldp+58,(vlSelf->axi4_top_tb__DOT__write_burst_incr_count),32);
    bufp->fullIData(oldp+59,(vlSelf->axi4_top_tb__DOT__write_burst_wrap_count),32);
    bufp->fullIData(oldp+60,(vlSelf->axi4_top_tb__DOT__write_size_byte_count),32);
    bufp->fullIData(oldp+61,(vlSelf->axi4_top_tb__DOT__write_size_halfword_count),32);
    bufp->fullIData(oldp+62,(vlSelf->axi4_top_tb__DOT__write_size_word_count),32);
    bufp->fullIData(oldp+63,(vlSelf->axi4_top_tb__DOT__write_resp_okay_count),32);
    bufp->fullIData(oldp+64,(vlSelf->axi4_top_tb__DOT__write_resp_exokay_count),32);
    bufp->fullIData(oldp+65,(vlSelf->axi4_top_tb__DOT__write_resp_slverr_count),32);
    bufp->fullIData(oldp+66,(vlSelf->axi4_top_tb__DOT__write_resp_decerr_count),32);
    bufp->fullIData(oldp+67,(vlSelf->axi4_top_tb__DOT__read_addr_low_count),32);
    bufp->fullIData(oldp+68,(vlSelf->axi4_top_tb__DOT__read_addr_mid_count),32);
    bufp->fullIData(oldp+69,(vlSelf->axi4_top_tb__DOT__read_addr_high_count),32);
    bufp->fullIData(oldp+70,(vlSelf->axi4_top_tb__DOT__read_burst_fixed_count),32);
    bufp->fullIData(oldp+71,(vlSelf->axi4_top_tb__DOT__read_burst_incr_count),32);
    bufp->fullIData(oldp+72,(vlSelf->axi4_top_tb__DOT__read_burst_wrap_count),32);
    bufp->fullIData(oldp+73,(vlSelf->axi4_top_tb__DOT__read_resp_okay_count),32);
    bufp->fullIData(oldp+74,(vlSelf->axi4_top_tb__DOT__read_resp_exokay_count),32);
    bufp->fullIData(oldp+75,(vlSelf->axi4_top_tb__DOT__read_resp_slverr_count),32);
    bufp->fullIData(oldp+76,(vlSelf->axi4_top_tb__DOT__read_resp_decerr_count),32);
    bufp->fullIData(oldp+77,(vlSelf->axi4_top_tb__DOT__aw_handshake_valid_ready_count),32);
    bufp->fullIData(oldp+78,(vlSelf->axi4_top_tb__DOT__w_handshake_valid_ready_count),32);
    bufp->fullIData(oldp+79,(vlSelf->axi4_top_tb__DOT__b_handshake_valid_ready_count),32);
    bufp->fullIData(oldp+80,(vlSelf->axi4_top_tb__DOT__ar_handshake_valid_ready_count),32);
    bufp->fullIData(oldp+81,(vlSelf->axi4_top_tb__DOT__r_handshake_valid_ready_count),32);
    bufp->fullIData(oldp+82,(vlSelf->axi4_top_tb__DOT__interrupt_idle_count),32);
    bufp->fullIData(oldp+83,(vlSelf->axi4_top_tb__DOT__interrupt_pending_count),32);
    bufp->fullIData(oldp+84,(vlSelf->axi4_top_tb__DOT__interrupt_acknowledged_count),32);
    bufp->fullBit(oldp+85,(vlSelf->axi4_top_tb__DOT__interrupt_req_prev));
    bufp->fullBit(oldp+86,(vlSelf->axi4_top_tb__DOT__interrupt_ack_prev));
    bufp->fullIData(oldp+87,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__burst_fixed_count),32);
    bufp->fullIData(oldp+88,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__burst_incr_count),32);
    bufp->fullIData(oldp+89,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__burst_wrap_count),32);
    bufp->fullIData(oldp+90,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__single_beat_write_count),32);
    bufp->fullIData(oldp+91,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__multi_beat_write_count),32);
    bufp->fullIData(oldp+92,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__single_beat_read_count),32);
    bufp->fullIData(oldp+93,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__multi_beat_read_count),32);
    bufp->fullIData(oldp+94,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__resp_okay_count),32);
    bufp->fullIData(oldp+95,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__resp_exokay_count),32);
    bufp->fullIData(oldp+96,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__resp_slverr_count),32);
    bufp->fullIData(oldp+97,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__resp_decerr_count),32);
    bufp->fullIData(oldp+98,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__aw_handshake_count),32);
    bufp->fullIData(oldp+99,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__w_handshake_count),32);
    bufp->fullIData(oldp+100,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__b_handshake_count),32);
    bufp->fullIData(oldp+101,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__ar_handshake_count),32);
    bufp->fullIData(oldp+102,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__r_handshake_count),32);
    bufp->fullIData(oldp+103,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__addr_region0_count),32);
    bufp->fullIData(oldp+104,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__addr_region1_count),32);
    bufp->fullIData(oldp+105,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__addr_region2_count),32);
    bufp->fullIData(oldp+106,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__addr_region3_count),32);
    bufp->fullIData(oldp+107,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__addr_out_of_range_count),32);
    bufp->fullIData(oldp+108,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__wstrb_full_count),32);
    bufp->fullIData(oldp+109,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__wstrb_partial_count),32);
    bufp->fullIData(oldp+110,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__wlast_asserted_count),32);
    bufp->fullIData(oldp+111,(vlSelf->axi4_top_tb__DOT__dut__DOT__coverage_monitor__DOT__rlast_asserted_count),32);
    bufp->fullIData(oldp+112,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_awaddr),32);
    bufp->fullCData(oldp+113,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_awlen),8);
    bufp->fullCData(oldp+114,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_awsize),3);
    bufp->fullCData(oldp+115,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_awburst),2);
    bufp->fullBit(oldp+116,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_awvalid));
    bufp->fullBit(oldp+117,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_awready));
    bufp->fullIData(oldp+118,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_wdata),32);
    bufp->fullCData(oldp+119,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_wstrb),4);
    bufp->fullBit(oldp+120,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_wlast));
    bufp->fullBit(oldp+121,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_wvalid));
    bufp->fullBit(oldp+122,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_wready));
    bufp->fullCData(oldp+123,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_bresp),2);
    bufp->fullBit(oldp+124,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_bvalid));
    bufp->fullBit(oldp+125,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_bready));
    bufp->fullIData(oldp+126,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_araddr),32);
    bufp->fullCData(oldp+127,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_arlen),8);
    bufp->fullCData(oldp+128,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_arsize),3);
    bufp->fullCData(oldp+129,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_arburst),2);
    bufp->fullBit(oldp+130,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_arvalid));
    bufp->fullBit(oldp+131,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_arready));
    bufp->fullIData(oldp+132,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_rdata),32);
    bufp->fullCData(oldp+133,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_rresp),2);
    bufp->fullBit(oldp+134,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_rlast));
    bufp->fullBit(oldp+135,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_rvalid));
    bufp->fullBit(oldp+136,(vlSelf->axi4_top_tb__DOT__dut__DOT__axi_rready));
    bufp->fullBit(oldp+137,(vlSelf->axi4_top_tb__DOT__dut__DOT__interrupt_ack));
    bufp->fullCData(oldp+138,(vlSelf->axi4_top_tb__DOT__dut__DOT__interrupt_ctrl__DOT__state),2);
    bufp->fullCData(oldp+139,(vlSelf->axi4_top_tb__DOT__dut__DOT__interrupt_ctrl__DOT__next_state),2);
    bufp->fullCData(oldp+140,(vlSelf->axi4_top_tb__DOT__dut__DOT__master__DOT__state),3);
    bufp->fullCData(oldp+141,(vlSelf->axi4_top_tb__DOT__dut__DOT__master__DOT__next_state),3);
    bufp->fullCData(oldp+142,(vlSelf->axi4_top_tb__DOT__dut__DOT__master__DOT__write_count),8);
    bufp->fullIData(oldp+143,(vlSelf->axi4_top_tb__DOT__dut__DOT__master__DOT__write_base_addr),32);
    bufp->fullCData(oldp+144,(vlSelf->axi4_top_tb__DOT__dut__DOT__master__DOT__write_length),8);
    bufp->fullCData(oldp+145,(vlSelf->axi4_top_tb__DOT__dut__DOT__master__DOT__write_size),3);
    bufp->fullCData(oldp+146,(vlSelf->axi4_top_tb__DOT__dut__DOT__master__DOT__write_burst),2);
    bufp->fullBit(oldp+147,(vlSelf->axi4_top_tb__DOT__dut__DOT__master__DOT__write_in_progress));
    bufp->fullCData(oldp+148,(vlSelf->axi4_top_tb__DOT__dut__DOT__master__DOT__read_count),8);
    bufp->fullIData(oldp+149,(vlSelf->axi4_top_tb__DOT__dut__DOT__master__DOT__read_base_addr),32);
    bufp->fullCData(oldp+150,(vlSelf->axi4_top_tb__DOT__dut__DOT__master__DOT__read_length),8);
    bufp->fullCData(oldp+151,(vlSelf->axi4_top_tb__DOT__dut__DOT__master__DOT__read_size),3);
    bufp->fullCData(oldp+152,(vlSelf->axi4_top_tb__DOT__dut__DOT__master__DOT__read_burst),2);
    bufp->fullBit(oldp+153,(vlSelf->axi4_top_tb__DOT__dut__DOT__master__DOT__read_in_progress));
    bufp->fullIData(oldp+154,(vlSelf->axi4_top_tb__DOT__dut__DOT__slave__DOT__write_addr),32);
    bufp->fullCData(oldp+155,(vlSelf->axi4_top_tb__DOT__dut__DOT__slave__DOT__write_len),8);
    bufp->fullCData(oldp+156,(vlSelf->axi4_top_tb__DOT__dut__DOT__slave__DOT__write_size),3);
    bufp->fullCData(oldp+157,(vlSelf->axi4_top_tb__DOT__dut__DOT__slave__DOT__write_burst),2);
    bufp->fullBit(oldp+158,(vlSelf->axi4_top_tb__DOT__dut__DOT__slave__DOT__write_addr_accepted));
    bufp->fullCData(oldp+159,(vlSelf->axi4_top_tb__DOT__dut__DOT__slave__DOT__write_count),8);
    bufp->fullBit(oldp+160,(vlSelf->axi4_top_tb__DOT__dut__DOT__slave__DOT__write_in_progress));
    bufp->fullBit(oldp+161,(vlSelf->axi4_top_tb__DOT__dut__DOT__slave__DOT__write_data_accepted));
    bufp->fullBit(oldp+162,(vlSelf->axi4_top_tb__DOT__dut__DOT__slave__DOT__write_response_pending));
    bufp->fullBit(oldp+163,(vlSelf->axi4_top_tb__DOT__dut__DOT__slave__DOT__write_response_ready));
    bufp->fullIData(oldp+164,(vlSelf->axi4_top_tb__DOT__dut__DOT__slave__DOT__current_addr),32);
    bufp->fullIData(oldp+165,(vlSelf->axi4_top_tb__DOT__dut__DOT__slave__DOT__addr_offset),32);
    bufp->fullIData(oldp+166,(vlSelf->axi4_top_tb__DOT__dut__DOT__slave__DOT__byte_size),32);
    bufp->fullIData(oldp+167,(vlSelf->axi4_top_tb__DOT__dut__DOT__slave__DOT__wrap_boundary),32);
    bufp->fullIData(oldp+168,(vlSelf->axi4_top_tb__DOT__dut__DOT__slave__DOT__aligned_addr),32);
    bufp->fullIData(oldp+169,(vlSelf->axi4_top_tb__DOT__dut__DOT__slave__DOT__mem_addr),32);
    bufp->fullIData(oldp+170,(vlSelf->axi4_top_tb__DOT__dut__DOT__slave__DOT__unnamedblk2__DOT__read_addr),32);
    bufp->fullBit(oldp+171,(vlSelf->axi4_top_tb__DOT__clk));
    bufp->fullBit(oldp+172,(vlSelf->axi4_top_tb__DOT__resetn));
    bufp->fullIData(oldp+173,(vlSelf->axi4_top_tb__DOT__dut__DOT__slave__DOT__unnamedblk1__DOT__i),32);
}
