// AXI4 Golden Reference Testbench - Comprehensive Test for All Four Modules
// This testbench tests: axi4_top, axi4_master, axi4_slave, and axi4_interrupt
// Location: verif/axi4_top_tb.sv
// This is the golden testbench used for grading reference

`timescale 1ns/1ps

module axi4_top_tb_golden;

    // Clock and Reset
    logic clk;
    logic resetn;
    
    // Clock generation
    initial begin
        clk = 0;
        forever #5 clk = ~clk; // 100MHz clock (10ns period)
    end
    
    // Reset generation
    initial begin
        resetn = 0;
        #100;
        resetn = 1;
        #5000;  // Extended simulation time for comprehensive testing
        $display("==========================================");
        $display("Simulation Complete");
        $display("==========================================");
        $display("Coverage Summary:");
        $display("  Write Transactions: %0d", write_transaction_count);
        $display("  Read Transactions: %0d", read_transaction_count);
        $display("  Write Address Handshakes: %0d", write_addr_handshake_count);
        $display("  Read Address Handshakes: %0d", read_addr_handshake_count);
        $display("  Write Response Handshakes: %0d", write_resp_handshake_count);
        $display("  Read Data Handshakes: %0d", read_data_handshake_count);
        $display("  Interrupt Requests: %0d", interrupt_request_count);
        $display("==========================================");
        $finish;
    end
    
    // Instantiate DUT (tests all four modules through top)
    axi4_top dut (
        .clk(clk),
        .resetn(resetn)
    );
    
    // ============================================
    // Test Stimuli for All Modules
    // ============================================
    
    // Manual Coverage Tracking Variables
    int write_transaction_count = 0;
    int read_transaction_count = 0;
    int write_addr_handshake_count = 0;
    int read_addr_handshake_count = 0;
    int write_resp_handshake_count = 0;
    int read_data_handshake_count = 0;
    int interrupt_request_count = 0;
    int assertion_pass_count = 0;
    int assertion_fail_count = 0;
    
    // Test stimulus for interrupt controller
    initial begin
        wait(resetn);
        #200;
        
        // Generate interrupt requests to test interrupt controller
        repeat (5) begin
            #100;
            interrupt_request_count++;
            dut.interrupt_req = 1;
            #50;
            dut.interrupt_req = 0;
            #50;
        end
    end
    
    // Note: AXI4 transactions are automatically generated by the master module
    // The master will start write and read transactions when in IDLE state
    // The testbench monitors these transactions and assertions will fire when they occur
    
    // ============================================
    // AXI4 Protocol Assertions - Icarus Compatible
    // ============================================
    // Note: Using immediate assertions and simpler syntax for Icarus Verilog compatibility
    
    // Track assertion states for protocol checks
    logic awvalid_asserted = 1'b0;
    logic wvalid_asserted = 1'b0;   // Added for WVALID stability
    logic bvalid_asserted = 1'b0;
    logic arvalid_asserted = 1'b0;
    logic rvalid_asserted = 1'b0;   // Added for RVALID stability
    logic wlast_seen = 1'b0;
    logic rlast_seen = 1'b0;
    logic interrupt_req_asserted = 1'b0;
    int write_data_complete_cycles = 0;
    int read_addr_cycles = 0;
    int interrupt_req_cycles = 0;
    int write_beat_count = 0;       // Track write beats for WLAST check
    int read_beat_count = 0;        // Track read beats for RLAST check
    
    // Timeout tracking for "signal never asserts" detection
    logic aw_handshake_done = 1'b0;  // AW phase complete, expect W
    int aw_to_w_timeout = 0;         // Cycles waiting for WVALID after AW
    logic ar_handshake_done = 1'b0;  // AR phase complete, expect R
    int ar_to_r_timeout = 0;         // Cycles waiting for RVALID after AR
    logic w_handshake_done = 1'b0;   // W phase complete, expect B
    int w_to_b_timeout = 0;          // Cycles waiting for BVALID after W
    
    // Constants for timeout values
    localparam int VALID_TIMEOUT = 50;  // Max cycles to wait for VALID signal
    
    // Assertion 1: Write Address Channel Handshake
    // AWVALID must remain asserted until AWREADY is asserted
    always @(posedge clk) begin
        if (resetn) begin
            if (dut.axi_awvalid && !awvalid_asserted) begin
                awvalid_asserted <= 1'b1;
            end
            if (dut.axi_awvalid && dut.axi_awready) begin
                awvalid_asserted <= 1'b0;
                assertion_pass_count++;
                $display("ASSERTION PASSED: AWVALID stable until AWREADY");
            end
            if (awvalid_asserted && !dut.axi_awvalid && !dut.axi_awready) begin
                assertion_fail_count++;
                $display("ASSERTION FAILED: AWVALID not stable until AWREADY");
                awvalid_asserted <= 1'b0;
            end
        end else begin
            awvalid_asserted <= 1'b0;
        end
    end
    
    // Assertion 2: Write Data Channel - WVALID must remain stable until WREADY
    always @(posedge clk) begin
        if (resetn) begin
            if (dut.axi_wvalid && !wvalid_asserted) begin
                wvalid_asserted <= 1'b1;
            end
            if (dut.axi_wvalid && dut.axi_wready) begin
                wvalid_asserted <= 1'b0;
                assertion_pass_count++;
                $display("ASSERTION PASSED: WVALID stable until WREADY");
            end
            if (wvalid_asserted && !dut.axi_wvalid && !dut.axi_wready) begin
                assertion_fail_count++;
                $display("ASSERTION FAILED: WVALID not stable until WREADY");
                wvalid_asserted <= 1'b0;
            end
        end else begin
            wvalid_asserted <= 1'b0;
        end
    end
    
    // Assertion 2b: WVALID timeout - must assert within timeout after AW handshake
    always @(posedge clk) begin
        if (resetn) begin
            // Track AW handshake completion
            if (dut.axi_awvalid && dut.axi_awready) begin
                aw_handshake_done <= 1'b1;
                aw_to_w_timeout <= 0;
            end
            // Count cycles waiting for WVALID
            if (aw_handshake_done && !dut.axi_wvalid) begin
                aw_to_w_timeout <= aw_to_w_timeout + 1;
                if (aw_to_w_timeout >= VALID_TIMEOUT) begin
                    assertion_fail_count++;
                    $display("ASSERTION FAILED: WVALID not stable until WREADY");
                    aw_handshake_done <= 1'b0;
                    aw_to_w_timeout <= 0;
                end
            end
            // Reset when W handshake completes
            if (dut.axi_wvalid && dut.axi_wready && dut.axi_wlast) begin
                aw_handshake_done <= 1'b0;
                aw_to_w_timeout <= 0;
            end
        end else begin
            aw_handshake_done <= 1'b0;
            aw_to_w_timeout <= 0;
        end
    end
    
    // Assertion 3: Write Data Channel - WLAST must be asserted on last beat
    always @(posedge clk) begin
        if (resetn) begin
            if (dut.axi_wvalid && dut.axi_wready) begin
                write_beat_count <= write_beat_count + 1;
                if (dut.axi_wlast) begin
                    wlast_seen <= 1'b1;
                    assertion_pass_count++;
                    $display("ASSERTION PASSED: WLAST correctly asserted");
                    write_beat_count <= 0;
                end
            end
            // Check if WLAST should have been asserted: BVALID without seeing WLAST
            if (dut.axi_bvalid && !wlast_seen && write_beat_count > 0) begin
                assertion_fail_count++;
                $display("ASSERTION FAILED: WLAST not asserted on final beat");
                wlast_seen <= 1'b0;
                write_beat_count <= 0;
            end
            // Reset seen flag after response
            if (dut.axi_bvalid && dut.axi_bready) begin
                wlast_seen <= 1'b0;
            end
        end else begin
            wlast_seen <= 1'b0;
            write_beat_count <= 0;
        end
    end
    
    // Assertion 4: Write Response Channel - BVALID must remain asserted until BREADY
    always @(posedge clk) begin
        if (resetn) begin
            if (dut.axi_bvalid && !bvalid_asserted) begin
                bvalid_asserted <= 1'b1;
            end
            if (dut.axi_bvalid && dut.axi_bready) begin
                bvalid_asserted <= 1'b0;
                assertion_pass_count++;
                $display("ASSERTION PASSED: BVALID stable until BREADY");
            end
            if (bvalid_asserted && !dut.axi_bvalid && !dut.axi_bready) begin
                assertion_fail_count++;
                $display("ASSERTION FAILED: BVALID not stable until BREADY");
                bvalid_asserted <= 1'b0;
            end
        end else begin
            bvalid_asserted <= 1'b0;
        end
    end
    
    // Assertion 4b: BVALID timeout - must assert within timeout after W handshake completes
    always @(posedge clk) begin
        if (resetn) begin
            // Track W handshake completion (WLAST)
            if (dut.axi_wvalid && dut.axi_wready && dut.axi_wlast) begin
                w_handshake_done <= 1'b1;
                w_to_b_timeout <= 0;
            end
            // Count cycles waiting for BVALID
            if (w_handshake_done && !dut.axi_bvalid) begin
                w_to_b_timeout <= w_to_b_timeout + 1;
                if (w_to_b_timeout >= VALID_TIMEOUT) begin
                    assertion_fail_count++;
                    $display("ASSERTION FAILED: BVALID not stable until BREADY");
                    w_handshake_done <= 1'b0;
                    w_to_b_timeout <= 0;
                end
            end
            // Reset when B handshake completes
            if (dut.axi_bvalid && dut.axi_bready) begin
                w_handshake_done <= 1'b0;
                w_to_b_timeout <= 0;
            end
        end else begin
            w_handshake_done <= 1'b0;
            w_to_b_timeout <= 0;
        end
    end
    
    // Assertion 5: Read Address Channel - ARVALID must remain stable until ARREADY
    always @(posedge clk) begin
        if (resetn) begin
            if (dut.axi_arvalid && !arvalid_asserted) begin
                arvalid_asserted <= 1'b1;
            end
            if (dut.axi_arvalid && dut.axi_arready) begin
                arvalid_asserted <= 1'b0;
                assertion_pass_count++;
                $display("ASSERTION PASSED: ARVALID stable until ARREADY");
            end
            if (arvalid_asserted && !dut.axi_arvalid && !dut.axi_arready) begin
                assertion_fail_count++;
                $display("ASSERTION FAILED: ARVALID not stable until ARREADY");
                arvalid_asserted <= 1'b0;
            end
        end else begin
            arvalid_asserted <= 1'b0;
        end
    end
    
    // Assertion 6: Read Data Channel - RVALID must remain stable until RREADY
    always @(posedge clk) begin
        if (resetn) begin
            if (dut.axi_rvalid && !rvalid_asserted) begin
                rvalid_asserted <= 1'b1;
            end
            if (dut.axi_rvalid && dut.axi_rready) begin
                rvalid_asserted <= 1'b0;
                assertion_pass_count++;
                $display("ASSERTION PASSED: RVALID stable until RREADY");
            end
            if (rvalid_asserted && !dut.axi_rvalid && !dut.axi_rready) begin
                assertion_fail_count++;
                $display("ASSERTION FAILED: RVALID not stable until RREADY");
                rvalid_asserted <= 1'b0;
            end
        end else begin
            rvalid_asserted <= 1'b0;
        end
    end
    
    // Assertion 6b: RVALID timeout - must assert within timeout after AR handshake
    always @(posedge clk) begin
        if (resetn) begin
            // Track AR handshake completion
            if (dut.axi_arvalid && dut.axi_arready) begin
                ar_handshake_done <= 1'b1;
                ar_to_r_timeout <= 0;
            end
            // Count cycles waiting for RVALID
            if (ar_handshake_done && !dut.axi_rvalid) begin
                ar_to_r_timeout <= ar_to_r_timeout + 1;
                if (ar_to_r_timeout >= VALID_TIMEOUT) begin
                    assertion_fail_count++;
                    $display("ASSERTION FAILED: RVALID not stable until RREADY");
                    ar_handshake_done <= 1'b0;
                    ar_to_r_timeout <= 0;
                end
            end
            // Reset when R handshake completes with RLAST
            if (dut.axi_rvalid && dut.axi_rready && dut.axi_rlast) begin
                ar_handshake_done <= 1'b0;
                ar_to_r_timeout <= 0;
            end
        end else begin
            ar_handshake_done <= 1'b0;
            ar_to_r_timeout <= 0;
        end
    end
    
    // Assertion 7: Write Response must come after write data completes
    always @(posedge clk) begin
        if (resetn) begin
            if (dut.axi_wvalid && dut.axi_wready && dut.axi_wlast) begin
                write_data_complete_cycles <= 1;
            end else if (write_data_complete_cycles > 0) begin
                write_data_complete_cycles <= write_data_complete_cycles + 1;
                if (dut.axi_bvalid) begin
                    assertion_pass_count++;
                    $display("ASSERTION PASSED: Write response received after data");
                    write_data_complete_cycles <= 0;
                end else if (write_data_complete_cycles > 20) begin
                    assertion_fail_count++;
                    $display("ASSERTION FAILED: Write response not received after data");
                    write_data_complete_cycles <= 0;
                end
            end
        end else begin
            write_data_complete_cycles <= 0;
        end
    end
    
    // Assertion 8: Read data must come after read address
    always @(posedge clk) begin
        if (resetn) begin
            if (dut.axi_arvalid && dut.axi_arready) begin
                read_addr_cycles <= 1;
            end else if (read_addr_cycles > 0) begin
                read_addr_cycles <= read_addr_cycles + 1;
                if (dut.axi_rvalid) begin
                    assertion_pass_count++;
                    $display("ASSERTION PASSED: Read data received after address");
                    read_addr_cycles <= 0;
                end else if (read_addr_cycles > 20) begin
                    assertion_fail_count++;
                    $display("ASSERTION FAILED: Read data not received after address");
                    read_addr_cycles <= 0;
                end
            end
        end else begin
            read_addr_cycles <= 0;
        end
    end
    
    // Assertion 9: Response codes are valid for write
    always @(posedge clk) begin
        if (resetn && dut.axi_bvalid) begin
            assert (dut.axi_bresp == 2'b00 || dut.axi_bresp == 2'b01 || 
                    dut.axi_bresp == 2'b10 || dut.axi_bresp == 2'b11) else begin
                assertion_fail_count++;
                $display("ASSERTION FAILED: Invalid BRESP code");
            end
            if (dut.axi_bresp == 2'b00 || dut.axi_bresp == 2'b01 || 
                dut.axi_bresp == 2'b10 || dut.axi_bresp == 2'b11) begin
                assertion_pass_count++;
                $display("ASSERTION PASSED: Valid BRESP code");
            end
        end
    end
    
    // Assertion 10: Response codes are valid for read
    always @(posedge clk) begin
        if (resetn && dut.axi_rvalid) begin
            assert (dut.axi_rresp == 2'b00 || dut.axi_rresp == 2'b01 || 
                    dut.axi_rresp == 2'b10 || dut.axi_rresp == 2'b11) else begin
                assertion_fail_count++;
                $display("ASSERTION FAILED: Invalid RRESP code");
            end
            if (dut.axi_rresp == 2'b00 || dut.axi_rresp == 2'b01 || 
                dut.axi_rresp == 2'b10 || dut.axi_rresp == 2'b11) begin
                assertion_pass_count++;
                $display("ASSERTION PASSED: Valid RRESP code");
            end
        end
    end
    
    // Assertion 11: RLAST must be asserted with last read data
    always @(posedge clk) begin
        if (resetn) begin
            if (dut.axi_rvalid && dut.axi_rlast && dut.axi_rready) begin
                rlast_seen <= 1'b1;
                read_beat_count <= 0;
                assertion_pass_count++;
                $display("ASSERTION PASSED: RLAST correctly asserted");
            end else if (dut.axi_rvalid && dut.axi_rready && !dut.axi_rlast) begin
                read_beat_count <= read_beat_count + 1;
                rlast_seen <= 1'b0;
            end
            // Check if RLAST was expected but transaction ended without it
            if (!dut.axi_rvalid && read_beat_count > 0 && !rlast_seen) begin
                assertion_fail_count++;
                $display("ASSERTION FAILED: RLAST not asserted on final beat");
                read_beat_count <= 0;
            end
        end else begin
            rlast_seen <= 1'b0;
            read_beat_count <= 0;
        end
    end
    
    // Assertion 12: Interrupt controller - ack should follow req
    always @(posedge clk) begin
        if (resetn) begin
            if (dut.interrupt_req && !interrupt_req_asserted) begin
                interrupt_req_asserted <= 1'b1;
                interrupt_req_cycles <= 1;
            end else if (interrupt_req_asserted) begin
                interrupt_req_cycles <= interrupt_req_cycles + 1;
                if (dut.interrupt_ack) begin
                    assertion_pass_count++;
                    $display("ASSERTION PASSED: Interrupt ack follows req");
                    interrupt_req_asserted <= 1'b0;
                    interrupt_req_cycles <= 0;
                end else if (interrupt_req_cycles > 10) begin
                    assertion_fail_count++;
                    $display("ASSERTION FAILED: Interrupt ack does not follow req");
                    interrupt_req_asserted <= 1'b0;
                    interrupt_req_cycles <= 0;
                end
            end
            if (!dut.interrupt_req) begin
                interrupt_req_asserted <= 1'b0;
                interrupt_req_cycles <= 0;
            end
        end else begin
            interrupt_req_asserted <= 1'b0;
            interrupt_req_cycles <= 0;
        end
    end
    
    // Assertion 11: Immediate assertion for protocol check
    always @(posedge clk) begin
        if (resetn) begin
            // Check that valid/ready handshakes are proper
            assert ((dut.axi_awvalid && dut.axi_awready) || (!dut.axi_awvalid)) else begin
                assertion_fail_count++;
                $display("ASSERTION FAILED: Invalid AW handshake state");
            end
        end
    end
    
    // Assertion 12: Reset behavior - fires once when reset is released
    logic reset_released = 1'b0;
    always @(posedge clk) begin
        if (resetn && !reset_released) begin
            reset_released <= 1'b1;
            assertion_pass_count++;
            $display("ASSERTION PASSED: Reset released, system active");
        end
    end
    
    // ============================================
    // Manual Coverage Tracking (Icarus Compatible)
    // ============================================
    // Using manual counters and flags instead of covergroups
    
    // Coverage bins tracking
    int write_addr_low_count = 0;
    int write_addr_mid_count = 0;
    int write_addr_high_count = 0;
    int write_burst_fixed_count = 0;
    int write_burst_incr_count = 0;
    int write_burst_wrap_count = 0;
    int write_size_byte_count = 0;
    int write_size_halfword_count = 0;
    int write_size_word_count = 0;
    int write_resp_okay_count = 0;
    int write_resp_exokay_count = 0;
    int write_resp_slverr_count = 0;
    int write_resp_decerr_count = 0;
    
    int read_addr_low_count = 0;
    int read_addr_mid_count = 0;
    int read_addr_high_count = 0;
    int read_burst_fixed_count = 0;
    int read_burst_incr_count = 0;
    int read_burst_wrap_count = 0;
    int read_resp_okay_count = 0;
    int read_resp_exokay_count = 0;
    int read_resp_slverr_count = 0;
    int read_resp_decerr_count = 0;
    
    int aw_handshake_valid_ready_count = 0;
    int w_handshake_valid_ready_count = 0;
    int b_handshake_valid_ready_count = 0;
    int ar_handshake_valid_ready_count = 0;
    int r_handshake_valid_ready_count = 0;
    
    int interrupt_idle_count = 0;
    int interrupt_pending_count = 0;
    int interrupt_acknowledged_count = 0;
    
    // Coverage tracking for write transactions
    always @(posedge clk) begin
        if (resetn && dut.axi_awvalid && dut.axi_awready) begin
            // Address coverage
            if (dut.axi_awaddr >= 32'h0000_0000 && dut.axi_awaddr <= 32'h0FFF_FFFF) begin
                write_addr_low_count++;
            end else if (dut.axi_awaddr >= 32'h1000_0000 && dut.axi_awaddr <= 32'h1FFF_FFFF) begin
                write_addr_mid_count++;
            end else begin
                write_addr_high_count++;
            end
            // Burst type coverage
            case (dut.axi_awburst)
                2'b00: write_burst_fixed_count++;
                2'b01: write_burst_incr_count++;
                2'b10: write_burst_wrap_count++;
            endcase
            // Size coverage
            case (dut.axi_awsize)
                3'b000: write_size_byte_count++;
                3'b001: write_size_halfword_count++;
                3'b010: write_size_word_count++;
            endcase
        end
    end
    
    // Coverage tracking for write responses
    always @(posedge clk) begin
        if (resetn && dut.axi_bvalid && dut.axi_bready) begin
            case (dut.axi_bresp)
                2'b00: write_resp_okay_count++;
                2'b01: write_resp_exokay_count++;
                2'b10: write_resp_slverr_count++;
                2'b11: write_resp_decerr_count++;
            endcase
        end
    end
    
    // Coverage tracking for read transactions
    always @(posedge clk) begin
        if (resetn && dut.axi_arvalid && dut.axi_arready) begin
            // Address coverage
            if (dut.axi_araddr >= 32'h0000_0000 && dut.axi_araddr <= 32'h0FFF_FFFF) begin
                read_addr_low_count++;
            end else if (dut.axi_araddr >= 32'h1000_0000 && dut.axi_araddr <= 32'h1FFF_FFFF) begin
                read_addr_mid_count++;
            end else begin
                read_addr_high_count++;
            end
            // Burst type coverage
            case (dut.axi_arburst)
                2'b00: read_burst_fixed_count++;
                2'b01: read_burst_incr_count++;
                2'b10: read_burst_wrap_count++;
            endcase
        end
    end
    
    // Coverage tracking for read responses
    always @(posedge clk) begin
        if (resetn && dut.axi_rvalid && dut.axi_rready) begin
            case (dut.axi_rresp)
                2'b00: read_resp_okay_count++;
                2'b01: read_resp_exokay_count++;
                2'b10: read_resp_slverr_count++;
                2'b11: read_resp_decerr_count++;
            endcase
        end
    end
    
    // Coverage tracking for handshakes
    always @(posedge clk) begin
        if (resetn) begin
            if (dut.axi_awvalid && dut.axi_awready) aw_handshake_valid_ready_count++;
            if (dut.axi_wvalid && dut.axi_wready) w_handshake_valid_ready_count++;
            if (dut.axi_bvalid && dut.axi_bready) b_handshake_valid_ready_count++;
            if (dut.axi_arvalid && dut.axi_arready) ar_handshake_valid_ready_count++;
            if (dut.axi_rvalid && dut.axi_rready) r_handshake_valid_ready_count++;
        end
    end
    
    // Coverage tracking for interrupt controller
    always @(posedge clk) begin
        if (resetn) begin
            case ({dut.interrupt_req, dut.interrupt_ack})
                2'b00: interrupt_idle_count++;
                2'b10: interrupt_pending_count++;
                2'b11: interrupt_acknowledged_count++;
            endcase
        end
    end
    
    // ============================================
    // Coverage and Transaction Monitoring
    // ============================================
    
    // Monitor write address handshake
    always @(posedge clk) begin
        if (resetn && dut.axi_awvalid && dut.axi_awready) begin
            write_addr_handshake_count++;
            write_transaction_count++;
            $display("[%0t] Write Address Handshake: 0x%08x, LEN=%0d, SIZE=%0d, BURST=%0d", 
                $time, dut.axi_awaddr, dut.axi_awlen, 
                dut.axi_awsize, dut.axi_awburst);
        end
    end
    
    // Monitor write data handshake
    always @(posedge clk) begin
        if (resetn && dut.axi_wvalid && dut.axi_wready) begin
            if (dut.axi_wlast) begin
                $display("[%0t] Write Data (LAST): 0x%08x, WSTRB=0x%01x", 
                    $time, dut.axi_wdata, dut.axi_wstrb);
            end else begin
                $display("[%0t] Write Data: 0x%08x, WSTRB=0x%01x", 
                    $time, dut.axi_wdata, dut.axi_wstrb);
            end
        end
    end
    
    // Monitor write response handshake
    always @(posedge clk) begin
        if (resetn && dut.axi_bvalid && dut.axi_bready) begin
            write_resp_handshake_count++;
            $display("[%0t] Write Response: BRESP=0x%02x", $time, dut.axi_bresp);
        end
    end
    
    // Monitor read address handshake
    always @(posedge clk) begin
        if (resetn && dut.axi_arvalid && dut.axi_arready) begin
            read_addr_handshake_count++;
            read_transaction_count++;
            $display("[%0t] Read Address Handshake: 0x%08x, LEN=%0d, SIZE=%0d, BURST=%0d", 
                $time, dut.axi_araddr, dut.axi_arlen, 
                dut.axi_arsize, dut.axi_arburst);
        end
    end
    
    // Monitor read data handshake
    always @(posedge clk) begin
        if (resetn && dut.axi_rvalid && dut.axi_rready) begin
            read_data_handshake_count++;
            $display("[%0t] Read Data: 0x%08x, RRESP=0x%02x, RLAST=%0d", 
                $time, dut.axi_rdata, dut.axi_rresp, 
                dut.axi_rlast);
        end
    end
    
    // Monitor interrupt controller
    // Icarus-compatible rising edge detection (replaces $rose())
    logic interrupt_req_prev = 1'b0;
    logic interrupt_ack_prev = 1'b0;
    always @(posedge clk) begin
        if (resetn) begin
            // Detect rising edge of interrupt_req
            if (dut.interrupt_req && !interrupt_req_prev) begin
                $display("[%0t] Interrupt Request asserted", $time);
            end
            interrupt_req_prev <= dut.interrupt_req;
            
            // Detect rising edge of interrupt_ack
            if (dut.interrupt_ack && !interrupt_ack_prev) begin
                $display("[%0t] Interrupt Acknowledged", $time);
            end
            interrupt_ack_prev <= dut.interrupt_ack;
        end else begin
            interrupt_req_prev <= 1'b0;
            interrupt_ack_prev <= 1'b0;
        end
    end
    
    // Coverage and monitoring
    initial begin
        $dumpfile("axi4_top_tb_golden.vcd");
        $dumpvars(0, axi4_top_tb_golden);
        $display("==========================================");
        $display("AXI4 Golden Testbench Started");
        $display("Testing: axi4_top, axi4_master, axi4_slave, axi4_interrupt");
        $display("==========================================");
        $display("Time: %0t", $time);
    end
    
    // Final coverage report
    final begin
        $display("==========================================");
        $display("Final Coverage Report");
        $display("==========================================");
        $display("Write Transactions: %0d", write_transaction_count);
        $display("Read Transactions: %0d", read_transaction_count);
        $display("Interrupt Requests: %0d", interrupt_request_count);
        $display("Total Assertions Passed: %0d", assertion_pass_count);
        $display("Total Assertions Failed: %0d", assertion_fail_count);
        $display("==========================================");
        $display("Coverage Statistics:");
        $display("  Write Address: Low=%0d, Mid=%0d, High=%0d", 
            write_addr_low_count, write_addr_mid_count, write_addr_high_count);
        $display("  Write Burst: Fixed=%0d, INCR=%0d, WRAP=%0d", 
            write_burst_fixed_count, write_burst_incr_count, write_burst_wrap_count);
        $display("  Write Responses: OKAY=%0d, EXOKAY=%0d, SLVERR=%0d, DECERR=%0d", 
            write_resp_okay_count, write_resp_exokay_count, 
            write_resp_slverr_count, write_resp_decerr_count);
        $display("  Read Address: Low=%0d, Mid=%0d, High=%0d", 
            read_addr_low_count, read_addr_mid_count, read_addr_high_count);
        $display("  Read Burst: Fixed=%0d, INCR=%0d, WRAP=%0d", 
            read_burst_fixed_count, read_burst_incr_count, read_burst_wrap_count);
        $display("  Handshakes: AW=%0d, W=%0d, B=%0d, AR=%0d, R=%0d", 
            aw_handshake_valid_ready_count, w_handshake_valid_ready_count,
            b_handshake_valid_ready_count, ar_handshake_valid_ready_count,
            r_handshake_valid_ready_count);
        $display("==========================================");
    end

endmodule


